apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ontoportal.fullname" . }}
  namespace: {{ include "ontoportal.namespace" . }}
  labels:
    {{- include "ontoportal.labels" . | nindent 4 }}
  {{- include "ontoportal.annotations" . | nindent 2 }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
