apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ontoportal-secrets
  namespace: ontoportal
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k3s-incluster-kubernetes
  target:
    name: ontoportal-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: apiKey
      remoteRef:
        key: ontoportal-prod-source
        property: apiKey
    - secretKey: adminPassword
      remoteRef:
        key: ontoportal-prod-source
        property: adminPassword
    - secretKey: mysqlRootPassword
      remoteRef:
        key: ontoportal-prod-source
        property: mysqlRootPassword
    - secretKey: storeDbaPassword
      remoteRef:
        key: ontoportal-prod-source
        property: storeDbaPassword
    - secretKey: storeDavPassword
      remoteRef:
        key: ontoportal-prod-source
        property: storeDavPassword
    - secretKey: matomoDbPassword
      remoteRef:
        key: ontoportal-prod-source
        property: matomoDbPassword
    - secretKey: matomoDbRootPassword
      remoteRef:
        key: ontoportal-prod-source
        property: matomoDbRootPassword
    - secretKey: mobiSyncInternalToken
      remoteRef:
        key: ontoportal-prod-source
        property: mobiSyncInternalToken
